// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoVegNB6CtbOzP78iaZAoRz780Dadby4',
    appId: '1:324137859967:web:b82a3d316205ed6962784a',
    messagingSenderId: '324137859967',
    projectId: 'groserytracker',
    authDomain: 'groserytracker.firebaseapp.com',
    storageBucket: 'groserytracker.firebasestorage.app',
    measurementId: 'G-DJ3YSSHCLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83CUApeKrZVS6FFuBc4dxaiPnP8PgG0c',
    appId: '1:324137859967:android:0057567c2516d36a62784a',
    messagingSenderId: '324137859967',
    projectId: 'groserytracker',
    storageBucket: 'groserytracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHoi4d6rsTI9vHDmKtF58zGyyd2-gZVo',
    appId: '1:324137859967:ios:8ed7cbff2bce869962784a',
    messagingSenderId: '324137859967',
    projectId: 'groserytracker',
    storageBucket: 'groserytracker.firebasestorage.app',
    iosBundleId: 'com.example.groceryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGHoi4d6rsTI9vHDmKtF58zGyyd2-gZVo',
    appId: '1:324137859967:ios:8ed7cbff2bce869962784a',
    messagingSenderId: '324137859967',
    projectId: 'groserytracker',
    storageBucket: 'groserytracker.firebasestorage.app',
    iosBundleId: 'com.example.groceryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcoVegNB6CtbOzP78iaZAoRz780Dadby4',
    appId: '1:324137859967:web:40cf2def2228d3d362784a',
    messagingSenderId: '324137859967',
    projectId: 'groserytracker',
    authDomain: 'groserytracker.firebaseapp.com',
    storageBucket: 'groserytracker.firebasestorage.app',
    measurementId: 'G-ZSESFS7LNT',
  );
}
